[package]
name = "homestream"
version = "0.0.0"
description = "HomeStream"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "homestream_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-http = { version = "2.0.0-rc", features = ["rustls-tls"] }
tokio = "1.39.2"
tauri-plugin-fs = "2.0.0-rc"
tauri-plugin-window-state = "2.0.0-rc"

[profile.dev]
incremental = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
